# Generated by Django 4.1.7 on 2023-07-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_id',
        ),
    ]
