# Generated by Django 4.1.7 on 2023-07-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_post_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dP',
            new_name='Profile',
        ),
    ]
