# Generated by Django 4.1.7 on 2023-07-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_convo_room_delete_chatroom_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),

    ]
