# Generated by Django 4.1.7 on 2023-07-25 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_room_messages_delete_chatroom_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.convo'),
        ),

    ]
