# Generated by Django 4.1.7 on 2023-07-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_room_messages_delete_chatroom_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
