# Generated by Django 4.1.7 on 2023-07-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_image_post_display_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image3',
            field=models.ImageField(default=None, upload_to='', verbose_name='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image4',
            field=models.ImageField(default=None, upload_to='', verbose_name='images/'),
        ),
    ]
