# Generated by Django 4.1.7 on 2023-08-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_profile_saved_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_posts',
        ),
    ]
