# Generated by Django 4.2.4 on 2023-08-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_profile_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_image',
            field=models.ImageField(upload_to='posts', verbose_name='Display Image'),
        ),
    ]
