# Generated by Django 4.2.4 on 2023-09-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_hashtag_post_pending_post_selling_post_sold_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='hashtag',
            new_name='category',
        ),
    ]
