# Generated by Django 4.2.4 on 2023-09-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_post_pending_remove_post_selling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=1000000),
        ),
    ]
