# Generated by Django 4.2.4 on 2023-10-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CLOTHING', 'CLOTHING'), ('FURNITURE', 'FURNITURE'), ('FREE STUFF', 'FREE STUFF'), ('VEHICLES', 'VEHICLES'), ('TECHNOLOGY', 'TECHNOLOGY'), ('HOBBIES', 'HOBBIES'), ('OFFICE SUPPLIES', 'OFFICE SUPPLIES'), ('DORM_GOODS', 'DORM_GOODS'), ('FOOD', 'FOOD'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('BOOKS', 'BOOKS'), ('MISC.', 'MISC.')], default='MISC.', max_length=15),
        ),
    ]
