# Generated by Django 4.2.4 on 2023-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='drafts',
            field=models.ManyToManyField(blank=True, related_name='drafts', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, to='myapp.post'),
        ),
    ]
