# Generated by Django 5.0 on 2023-12-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0054_alter_profile_drafts_alter_profile_saved_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="purchased_by",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="buy_history",
            field=models.ManyToManyField(
                blank=True, related_name="buy_history", to="myapp.post"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="liked_posts",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to="myapp.post"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="saved_posts",
            field=models.ManyToManyField(
                blank=True, related_name="saved_posts", to="myapp.post"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="buyer_profile_picture",
            field=models.ImageField(upload_to="images/", verbose_name="buyer_picture"),
        ),
        migrations.AlterField(
            model_name="room",
            name="seller_profile_picture",
            field=models.ImageField(upload_to="images/", verbose_name="seller_picture"),
        ),
    ]
