# Generated by Django 5.0 on 2023-12-21 22:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0055_post_purchased_by_profile_buy_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.profile",
                    ),
                ),
                ("new_messages", models.BooleanField(blank=True, default=False)),
                ("liked_posts_updates", models.BooleanField(blank=True, default=False)),
                ("scamming", models.BooleanField(blank=True, default=False)),
                ("illegal_goods", models.BooleanField(blank=True, default=False)),
                (
                    "blocked_users",
                    models.ManyToManyField(
                        blank=True, related_name="blocked_users", to="myapp.profile"
                    ),
                ),
            ],
        ),
    ]
