# Generated by Django 5.0 on 2023-12-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0058_report_post_alter_report_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="post",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="myapp.post",
            ),
        ),
    ]
