# Generated by Django 5.0 on 2023-12-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0059_alter_report_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="myapp.profile",
            ),
        ),
    ]
