# Generated by Django 5.0 on 2023-12-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0060_alter_report_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="id",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_joined_date",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="post",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="myapp.post",
            ),
        ),
    ]
