# Generated by Django 5.0 on 2024-01-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0062_profile_email_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(default="none@wm.edu"),
        ),
    ]
