# Generated by Django 5.0 on 2024-01-06 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0064_flaggedposts_ratings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FlaggedPosts",
            new_name="FlaggedPost",
        ),
        migrations.RenameModel(
            old_name="Ratings",
            new_name="Rating",
        ),
    ]
