# Generated by Django 5.0 on 2024-01-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0065_rename_flaggedposts_flaggedpost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="flag",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
