# Generated by Django 5.0 on 2024-01-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0066_post_flag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="already_sold",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="damaged_product",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="harassment",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="illegal_goods",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="language",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="noShow",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="postName",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="scamming",
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SCAMMING", "SCAMMING"),
                            ("HARASSMENT", "HARASSMENT"),
                            ("ILLEGAL GOODS", "ILLEGAL GOODS"),
                            ("NICKNAME", "NICKNAME"),
                            ("LANGUAGE", "LANGUAGE"),
                            ("NO SHOW", "NO SHOW"),
                            ("POST NAME", "POST NAME"),
                            ("DAMAGED PRODUCT", "DAMAGED PRODUCT"),
                            ("ALREADY SOLD", "ALREADY SOLD"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violation_username",
                        to="myapp.profile",
                    ),
                ),
            ],
        ),
    ]
