# Generated by Django 5.0 on 2024-01-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0067_remove_usersettings_already_sold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="violation",
            name="appeal",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
