# Generated by Django 4.1.7 on 2023-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_post_photo_id_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=-1)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_id',
            field=models.IntegerField(default=-1),
        ),
    ]
