# Generated by Django 4.1.7 on 2023-07-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_postcount_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
