# Generated by Django 4.2.4 on 2023-09-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_post_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='drafts',
            field=models.ManyToManyField(related_name='drafts', to='myapp.post'),
        ),
    ]
