# Generated by Django 4.2.4 on 2023-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='post',
            name='selling',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sold',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('SELLING', 'SELLING'), ('PENDING', 'PENDING'), ('SOLD', 'SOLD')], default='SELLING', max_length=8),
        ),
    ]
