# Generated by Django 4.2.4 on 2023-10-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_message_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
